Lectures/Django/Lecture0/Lecture0/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

Lectures/Django/Lecture0/hello/urls.py
from django.urls import path
from . import views

app_name = "hello"
urlpatterns = [
    path("", views.index, name="index"),
    path("request", views.request, name="request"),
    path("example", views.example, name="example"),
]

Lectures/Django/Lecture0/newyear/urls.py
from django.urls import path
from . import views

app_name = "newyear"
urlpatterns = [
    path("", views.index, name="index")
]

Lectures/Django/Lecture0/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
   path("", views.index, name="index"),
   path("add", views.add, name="add")
]

Lectures/Django/Lecture0/hello/models.py
from django.db import models

# Create your models here.

Lectures/Django/Lecture0/newyear/models.py
from django.db import models

# Create your models here.

Lectures/Django/Lecture0/tasks/models.py
from django.db import models

# Create your models here.

Lectures/Django/Lecture0/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def request(request):
    return HttpResponse("This is a request in django.")

def example(request):
    return HttpResponse("This is an example of a HTTPResponse in django.")

Lectures/Django/Lecture0/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    date = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": date.month == 1 and date.day ==1
    })

Lectures/Django/Lecture0/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms

## VARIABLES ##
class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task ")

    
## VIEWS ##
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
        
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
        
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

Lectures/Django/Lecture0/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang=""en>
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, {{ name }}</h1>
    </body>
</html>

Lectures/Django/Lecture0/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang=""en>
    <head>
        <title>Hello World!</title>
    </head>
    
    <body>
        <h1>Hello, world!</h1>
        <a href="{% url 'hello:request' %}">Request Example</a> <br>
        <a href="{% url 'hello:example' %}">HTTPResponse Example</a> <br>
        <a href="{% url 'newyear:index' %}">Is today a new year?</a> <br>
        <a href="{% url 'tasks:index' %}">Tasks App</a>
    </body>
</html>

Lectures/Django/Lecture0/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is today a new year?</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet"></link>
    </head>
    <body>
        <h1>Is today a new year?</h1>

        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>No</h1>
        {% endif %}
    </body>
</html>

Lectures/Django/Lecture0/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block head %}
    <title>Add a task.</title>
{% endblock %}

{% block body %}
    <h1>Add a new task:</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }} 
        <input type="submit">
    </form> <br>
    <a href="{% url 'tasks:index' %}">Return to list.</a>
{% endblock %}

Lectures/Django/Lecture0/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block head %}
    <title>Tasks</title>
{% endblock %}

{% block body %}
    <h1>Tasks</h1>

    <div class="container.lg">
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% endfor %}
        </ul>
        <a href="{% url 'tasks:add' %}">Add a new task.</a> <br>
    </div>
{% endblock %}

Lectures/Django/Lecture0/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>